# Generated by Django 4.2.2 on 2023-06-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_products_cart_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.ManyToManyField(related_name='product_cart', to='api.product'),
        ),
    ]
