# Generated by Django 4.2.2 on 2023-06-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='products',
        ),
    ]
